[package]
name = "mail"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-FCL-1.0-ALv2"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
mail-builder = { workspace = true }
mailparse = { workspace = true }
message-ir = { path = "../ir" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
