@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' !$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
' !include $ICONURL/common.puml
' !include $ICONURL/font-awesome/directory_open_o.puml
' FA_DIRECTORY_OPEN_O(d1)

LAYOUT_TOP_DOWN()
' LAYOUT_LEFT_RIGHT()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()


title Container Diagram: Message Crate

Person(user, "User", "A person who wants to store messages from a device or platform.")
Container_Ext(data, "Raw Message Data", "device backup, .json, .xml, .csv", "Extracted messages from a device or service")
' Container_Ext($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="", $baseShape="rectangle")

' !unquoted procedure Container_Boundary($alias, $label, $tags="", $link="", $descr = "")
Container_Boundary(message_crate_system, "Message Crate System") {
    Container(web, "Static Web Content", "html, css, javscript")
    
    Container_Boundary(ui, "User Interface") {
      Container(spa, "Webpage", "Web UI. React + Vite + web", "Single-page app for working with the message backend. No import or export functionality.")      
      Container(desktop, "Desktop App", "Web UI. Tauri + React + web", "Single-page app for working with the message backend. Allows importing and exporting messages.")
      ' Container(desktop, "Desktop App", "Tauri + React + web", "Native window. Extract and Format write files on disk. Import and browse call the API.")
      ' Container(spa, "Webpage", "React + Vite + web", "Same SPA in the browser at http://127.0.0.1:8080 and inside the Tauri WebView")
    }

    Container(backend, "Backend", "Rust, Axum", "Provides API endpoints for authentication, storing and retrieving data, and searching.")    
    ContainerDb(db, "Database", "SQLite", "User account information, messages, contacts, etc.")
    Container(attachments, "Attachment Storage", "image, video, audio files", "Message attachments stored per account.")
}

' Rel(desktop, spa, "Embeds in WebView")
' Rel(desktop, backend, "HTTP /v1")
' Rel_U(spa, backend, "GET / and /v1")
Rel(user, data, "Creates")
Rel_R(user, ui, "Use")
Rel_R(backend, data, "Imports messages", "json, https")

Rel(web, ui, "Delivers")
Rel(ui, backend, "Makes API request", "json, https")
Rel(backend, db, "Reads and writes", "rusqlite")
Rel(backend, attachments, "Reads and writes", "file")

' new C4-Plantuml version details (incl. PlantUML version) as table
C4VersionDetails()

' version functions used in e.g. footer
' footer drawn with PlantUML v. %version() and C4-PlantUML v. C4Version()
@enduml