// DO NOT EDIT — generated by scripts/sync-schema.mjs
// Source: schema/sql/*.sql

export const ACCOUNTS_DDL = `-- Login account (web UI + API owner).
CREATE TABLE IF NOT EXISTS accounts (
    -- Account id. Ids below 100 are reserved for accounts the server makes
    -- itself: the owner is 1 and the demo account 2. Every other account takes
    -- the next id above both that range and the highest id the table has ever
    -- held. AUTOINCREMENT keeps that high mark in sqlite_sequence, so a
    -- deleted account's id, and any directory of its files left behind, never
    -- passes to a new account.
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- Login user id; unique case-insensitively.
    username TEXT NOT NULL UNIQUE COLLATE NOCASE,
    -- Password verifier hash; NULL when password auth is unused.
    password_hash TEXT,
    -- Display name for “you” in the UI.
    preferred_name TEXT,
    -- IANA time zone (for example America/New_York) every message time, day and year is
    -- read in. Chosen at profile setup; a message records only the instant it arrived.
    time_zone TEXT NOT NULL DEFAULT 'UTC',
    -- 1 = may not log in and existing sessions are refused; 0 = active.
    disabled INTEGER NOT NULL DEFAULT 0,
    -- 1 = the account holder has not set up their profile yet, so the session
    -- owes profile setup before it goes anywhere; cleared on the first save.
    must_set_up_profile INTEGER NOT NULL DEFAULT 0,
    -- 1 = may call the import endpoints.
    can_import INTEGER NOT NULL DEFAULT 1,
    -- 1 = may call the export endpoints.
    can_export INTEGER NOT NULL DEFAULT 1,
    -- 1 = may destroy message data for good (delete from the trash, empty it,
    -- and delete the account's messages).
    can_delete INTEGER NOT NULL DEFAULT 1,
    -- RFC 3339 UTC instant of the last successful login (login, claiming
    -- Message Crate, or registering); NULL until the account has logged in once.
    last_login_at TEXT
);

-- Handles that mean “me” when matching message participants.
CREATE TABLE IF NOT EXISTS account_handles (
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Self identity (\`handles.id\`).
    handle_id INTEGER NOT NULL REFERENCES handles(id) ON DELETE CASCADE,
    PRIMARY KEY (account_id, handle_id)
);

-- GUI session Bearer (one per account; rotates on login). Prefix: mc-user-
CREATE TABLE IF NOT EXISTS account_session_tokens (
    -- Owning account (\`accounts.id\`); also the primary key (one session).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Hash of the session Bearer secret (never store the raw token).
    token_hash TEXT NOT NULL UNIQUE,
    -- Unix-seconds string for when this session token was issued.
    created_at TEXT NOT NULL,
    -- Unix-seconds string; session rejected after this time.
    expires_at TEXT NOT NULL,
    -- Which app last used this session: 'desktop' or 'website'. NULL until a
    -- request names one.
    app_kind TEXT,
    -- The Build that app reported, e.g. '0.9.0+343fe0d8'. Set with app_kind,
    -- and rewritten only when either differs from what a request sends.
    app_build TEXT,
    -- The Audit Trail's \`logged_in\` entry for this session
    -- (\`audit_entries.id\`), so the entry that ends it can name it. NULL for a
    -- session made outside a login, such as a test's.
    login_entry_id INTEGER REFERENCES audit_entries(id),
    PRIMARY KEY (account_id)
);

-- Named API tokens (many per account). Prefix: mc-api-
CREATE TABLE IF NOT EXISTS account_api_tokens (
    -- Token id.
    id INTEGER PRIMARY KEY,
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- User-visible label in Settings.
    label TEXT NOT NULL,
    -- Hash of the API Bearer secret (never store the raw token).
    token_hash TEXT NOT NULL UNIQUE,
    -- 1 = this token may call the import endpoints.
    can_import INTEGER NOT NULL DEFAULT 1,
    -- 1 = this token may call the export endpoints.
    can_export INTEGER NOT NULL DEFAULT 1,
    -- Masked form for Settings (e.g. mc-api-Sd..mE). Not enough to recover the secret.
    token_hint TEXT NOT NULL DEFAULT 'mc-api-..',
    -- Unix-seconds string for when this API token was created.
    created_at TEXT NOT NULL,
    -- Unix-seconds string; NULL until first successful Bearer use.
    last_accessed_at TEXT,
    -- Unix-seconds string; NULL means no expiry.
    expires_at TEXT,
    -- Soft-disable without deleting the row.
    disabled INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_account_api_tokens_account
    ON account_api_tokens(account_id);

-- Per-account key/value preferences for the UI and server.
CREATE TABLE IF NOT EXISTS account_prefs (
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Preference name (for example theme or feature flags).
    key TEXT NOT NULL,
    -- Preference value stored as text.
    value TEXT NOT NULL,
    PRIMARY KEY (account_id, key)
);

-- Settings that belong to the whole Message Crate rather than to one account. Exactly
-- one row, so the owner reads and writes it without an id.
CREATE TABLE IF NOT EXISTS server_settings (
    -- Always 1: a Message Crate has one settings record.
    id INTEGER PRIMARY KEY CHECK (id = 1),
    -- 1 = anyone reaching the server may create their own account; 0 = only
    -- the owner creates accounts. Off until the owner turns it on.
    public_registration INTEGER NOT NULL DEFAULT 0,
    -- The attachment size limit: the largest asset the server accepts, in
    -- bytes. 512 MiB until the owner sets it.
    asset_max_bytes BIGINT NOT NULL DEFAULT 536870912
);

-- A Demo Account build that has not finished. A build writes this row before
-- it writes anything else and removes it after its last write, so a row found
-- when the server starts is a build the server stopped part-way: the server
-- removes the Demo Account the build left and reports the build as failed.
CREATE TABLE IF NOT EXISTS demo_account_build (
    -- Always 1: one Demo Account build runs at a time.
    id INTEGER PRIMARY KEY CHECK (id = 1),
    -- When the build started, in Unix seconds as text.
    started_at TEXT NOT NULL
);

-- Process-wide schema markers (for example FTS trigger install flag).
CREATE TABLE IF NOT EXISTS schema_meta (
    -- Marker name (for example messages_fts_triggers_v1).
    key TEXT PRIMARY KEY,
    -- Marker value (usually '1' when installed).
    value TEXT NOT NULL
);

-- One row per import run into Message Crate.
CREATE TABLE IF NOT EXISTS imports (
    -- Surrogate primary key for this import run.
    id INTEGER PRIMARY KEY,
    -- Owning account (\`accounts.id\`). Set NULL when the account is deleted:
    -- the run is part of the Audit Trail, which outlives the account
    -- (docs/adr/0020-the-audit-trail-outlives-the-account.md).
    account_id INTEGER REFERENCES accounts(id) ON DELETE SET NULL,
    -- The username the account had, written when the account is deleted and
    -- \`account_id\` becomes NULL, so the run still says whose it was.
    username TEXT,
    -- The \`account_deleted\` entry (\`audit_entries.id\`) of the account, written
    -- when it is deleted, so the run reads with that account's other entries
    -- and apart from a later account given the same username.
    deletion_entry_id INTEGER REFERENCES audit_entries(id),
    -- What started the run: 'session' or 'api_token'. NULL for a run the
    -- server started itself (the Demo Account build, the CLI import).
    credential TEXT,
    -- The app the starting Session named: 'desktop' or 'website'. NULL when
    -- the request named none or a token started the run.
    app_kind TEXT,
    -- That app's Build, such as '0.9.0+343fe0d8'; set with app_kind.
    app_build TEXT,
    -- The starting API token's label as it was then, so the run names the
    -- token after it is renamed or deleted.
    api_token_label TEXT,
    -- The starting API token's masked hint (mc-api-Sd..mE) as it was then.
    -- Never the token or its hash.
    api_token_hint TEXT,
    -- Backup/source family (for example imessage, whatsapp, sms-backup-restore).
    source TEXT NOT NULL,
    -- Client/tool name that performed the import (optional).
    tool TEXT,
    -- Import mode string recorded by the importer.
    mode TEXT NOT NULL,
    -- 1 when cross-source dedupe runs after each batch of this run. Stated
    -- once, when the run is created, so two batches cannot disagree.
    dedupe INTEGER NOT NULL DEFAULT 0,
    -- Run status (for example running, completed, failed, cancelled).
    status TEXT NOT NULL,
    -- When the import started.
    started_at TEXT NOT NULL,
    -- When the import finished; NULL while still running.
    finished_at TEXT,
    -- Messages accepted during this run.
    message_count INTEGER NOT NULL DEFAULT 0,
    -- Attachments accepted during this run.
    attachment_count INTEGER NOT NULL DEFAULT 0,
    -- Bytes uploaded for assets during this run.
    bytes_uploaded INTEGER NOT NULL DEFAULT 0,
    -- Wall-clock duration of the whole run in milliseconds.
    duration_ms INTEGER,
    -- Time spent parsing input in milliseconds.
    parse_ms INTEGER,
    -- Time spent copying, converting, or skipping attachments in milliseconds.
    attachments_ms INTEGER,
    -- Time spent preparing conversation files in milliseconds.
    prepare_ms INTEGER,
    -- Time spent uploading in milliseconds.
    upload_ms INTEGER,
    -- JSON blob with a human-readable run summary for Import History.
    summary_json TEXT,
    -- Where a running Import Run is: parse, write, staging_review, media,
    -- media_review, or upload. NULL once the run is over. \`status\` says
    -- how a run ended; \`stage\` says where it is.
    stage TEXT,
    -- Absolute path to this run's directory in the Staging Directory on the client. The
    -- database holds the pointer so resuming means asking the server where
    -- to go, rather than guessing from a directory listing.
    run_dir TEXT,
    -- Which install created the run, so another machine can say where
    -- it belongs instead of failing to open a path that was never local.
    device_id TEXT,
    -- Import form snapshot: restores the screen, and restarts the run with
    -- the same settings.
    form_json TEXT,
    -- Source path, size, mtime, and message count. A backup that grew
    -- between attempts has different conversation boundaries.
    source_fingerprint TEXT,
    -- Addresses the backup's device sent from (JSON array), read by the
    -- client before parsing. Lets a resumed Staging Review show the identity
    -- list without re-reading the backup.
    source_identities TEXT,
    -- When the backup the run read was made, in the form messages.timestamp
    -- holds: the newest its conversation files name. NULL until a file that
    -- says is imported, and for a run whose files say nothing.
    backup_taken_at TEXT
);

CREATE INDEX IF NOT EXISTS ix_imports_account_started
    ON imports(account_id, started_at DESC);

-- At most one running Import Run per account. A partial unique index
-- rather than application logic, so it holds against a racing client.
CREATE UNIQUE INDEX IF NOT EXISTS ux_imports_active_account
    ON imports(account_id) WHERE status = 'running';

-- One row per Export Run: what was asked for and how much matched, never
-- message content. Recorded permanently whether the run completed, failed
-- or was cancelled, so every read of message data by a program leaves a
-- record.
CREATE TABLE IF NOT EXISTS exports (
    -- Surrogate primary key for this export run.
    id INTEGER PRIMARY KEY,
    -- Owning account (\`accounts.id\`). Set NULL when the account is deleted,
    -- as for \`imports\`; the deletion also clears \`scope_query\`,
    -- \`scope_conversation_ids\` and \`scope_message_ids\`, which describe the
    -- person's messages.
    account_id INTEGER REFERENCES accounts(id) ON DELETE SET NULL,
    -- The username the account had, written when the account is deleted and
    -- \`account_id\` becomes NULL, so the run still says whose it was.
    username TEXT,
    -- The \`account_deleted\` entry (\`audit_entries.id\`) of the account, written
    -- when it is deleted, so the run reads with that account's other entries
    -- and apart from a later account given the same username.
    deletion_entry_id INTEGER REFERENCES audit_entries(id),
    -- What started the run: 'session' or 'api_token'. NULL for a run the
    -- server started itself (the Demo Account build, the CLI import).
    credential TEXT,
    -- The app the starting Session named: 'desktop' or 'website'. NULL when
    -- the request named none or a token started the run.
    app_kind TEXT,
    -- That app's Build, such as '0.9.0+343fe0d8'; set with app_kind.
    app_build TEXT,
    -- The starting API token's label as it was then, so the run names the
    -- token after it is renamed or deleted.
    api_token_label TEXT,
    -- The starting API token's masked hint (mc-api-Sd..mE) as it was then.
    -- Never the token or its hash.
    api_token_hint TEXT,
    -- Which of the three scope forms the run asked for: everything, query,
    -- or selection.
    scope_kind TEXT NOT NULL,
    -- Which list the query is for, when \`scope_kind\` is query: conversations
    -- (every message of the conversations the query shows) or messages (the
    -- messages the query matches); NULL otherwise.
    scope_list TEXT,
    -- The search-language query, when \`scope_kind\` is query; NULL otherwise.
    scope_query TEXT,
    -- JSON array of the conversation ids picked by hand, when \`scope_kind\`
    -- is selection; NULL otherwise.
    scope_conversation_ids TEXT,
    -- JSON array of the message ids picked by hand, when \`scope_kind\` is
    -- selection; NULL otherwise.
    scope_message_ids TEXT,
    -- Client/tool name that ran the export (optional).
    tool TEXT,
    -- Run status: running, completed, failed, or cancelled.
    status TEXT NOT NULL,
    -- When the export started.
    started_at TEXT NOT NULL,
    -- When the export finished; NULL while still running.
    finished_at TEXT,
    -- Messages the scope matched when the run was created.
    message_count INTEGER NOT NULL,
    -- Distinct conversations with at least one matching message, at creation.
    conversation_count INTEGER NOT NULL,
    -- Distinct attachment fingerprints among the matching messages, at creation.
    attachment_count INTEGER NOT NULL,
    -- Sum of the known sizes of those distinct attachments, at creation.
    total_bytes INTEGER NOT NULL,
    -- How far the run's message pages have read into its list, in places,
    -- so an abandoned run shows how far it got.
    messages_delivered INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_exports_account_started
    ON exports(account_id, started_at DESC);

-- Per-item error or skip recorded during an import run.
CREATE TABLE IF NOT EXISTS import_issues (
    -- Surrogate primary key for this issue row.
    id INTEGER PRIMARY KEY,
    -- Parent import run (\`imports.id\`).
    import_id INTEGER NOT NULL REFERENCES imports(id) ON DELETE CASCADE,
    -- Issue class: 'error' or 'skip'.
    kind TEXT NOT NULL,
    -- Stage the issue came from: staging, media, or upload.
    stage TEXT NOT NULL,
    -- Item identifier (path, guid, or similar).
    item TEXT NOT NULL,
    -- Human-readable explanation.
    reason TEXT NOT NULL,
    -- When the issue was recorded.
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_import_issues_import
    ON import_issues(import_id);

-- Per-item note recorded during an import run: something the run did that
-- is worth knowing but did not fail, such as a message it kept with a
-- caveat. Kept apart from \`import_issues\`, so a note never reads as an
-- Import Error or makes a run \`completed_with_issues\`.
CREATE TABLE IF NOT EXISTS import_notes (
    -- Surrogate primary key for this note row.
    id INTEGER PRIMARY KEY,
    -- Parent import run (\`imports.id\`).
    import_id INTEGER NOT NULL REFERENCES imports(id) ON DELETE CASCADE,
    -- Stage the note came from: staging, media, or upload.
    stage TEXT NOT NULL,
    -- Item identifier (path, address, or similar).
    item TEXT NOT NULL,
    -- What the run did with the item, in one sentence.
    text TEXT NOT NULL,
    -- When the note was recorded.
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_import_notes_import
    ON import_notes(import_id);

-- What one import run did to one contact. Written while the run stages, so
-- the record says what the import decided rather than what timestamps
-- suggest afterwards. The run's Contact Group and its new/changed counts
-- read this table.
CREATE TABLE IF NOT EXISTS import_contacts (
    -- Import run (\`imports.id\`).
    import_id INTEGER NOT NULL REFERENCES imports(id) ON DELETE CASCADE,
    -- Contact the run touched (\`contacts.id\`); the row goes with the contact.
    contact_id INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    -- One of replaced_trashed, created, named, identity_added. When a run does
    -- more than one of these to a contact, the earlier one in that list is
    -- kept.
    reason TEXT NOT NULL,
    PRIMARY KEY (import_id, contact_id)
);

CREATE INDEX IF NOT EXISTS ix_import_contacts_contact
    ON import_contacts(contact_id);

-- The Audit Trail: what each user did on this Message Crate, and when, for
-- everything \`imports\` and \`exports\` do not already record. An entry is
-- written once and never changed by a route; deleting an account sets its
-- \`account_id\` NULL and keeps the entry
-- (docs/adr/0020-the-audit-trail-outlives-the-account.md). A password, a
-- session token and an API token never enter it, hashed or not, and nothing
-- here says what a message said or which conversation it was in.
CREATE TABLE IF NOT EXISTS audit_entries (
    -- Entry id.
    id INTEGER PRIMARY KEY,
    -- When it happened, RFC 3339 UTC, as \`imports.started_at\` is written.
    at TEXT NOT NULL,
    -- What happened: logged_in, session_ended, login_refused,
    -- account_created, account_disabled, account_enabled, password_set,
    -- permissions_changed, messages_deleted, conversation_deleted,
    -- trash_emptied, account_deleted, registration_opened,
    -- registration_closed, api_token_created, api_token_deleted,
    -- address_book_loaded or address_book_exported.
    action TEXT NOT NULL,
    -- Who acted: owner, holder (the account's own holder), command_line
    -- (a server command), server (the server on its own), or anonymous
    -- (someone at the login card).
    actor TEXT NOT NULL,
    -- The account the entry is about (\`accounts.id\`). NULL when it is about
    -- no account (a refused login for an unknown username, opening or closing
    -- registration) or once the account is deleted.
    account_id INTEGER REFERENCES accounts(id) ON DELETE SET NULL,
    -- That account's username when the entry was written; for a refused
    -- login, the username as typed, trimmed and cut to 128 characters.
    username TEXT,
    -- The \`account_deleted\` entry of the account the entry is about, written
    -- on every entry about it when it is deleted, that entry included. A
    -- deleted account is read by it: its id outlives it no other way, and
    -- its username may pass to a later account.
    deletion_entry_id INTEGER REFERENCES audit_entries(id),
    -- session_ended: logged_out, replaced or revoked. login_refused:
    -- unknown_username, wrong_password or account_disabled. NULL otherwise.
    reason TEXT,
    -- logged_in and login_refused: the app the request named, 'desktop' or
    -- 'website'; NULL when the request named none.
    app_kind TEXT,
    -- That app's Build; set with app_kind.
    app_build TEXT,
    -- session_ended: the logged_in entry of the session that ended.
    -- password_set by the holder: the logged_in entry of the session the
    -- change renewed.
    session_entry_id INTEGER REFERENCES audit_entries(id),
    -- logged_in: when the session expires, RFC 3339 UTC. password_set by the
    -- holder: when the renewed session expires. A session with no
    -- session_ended entry reads as expired from the latest of these, so
    -- expiry needs no entry and no sweeper, and no entry is ever changed.
    session_expires_at TEXT,
    -- JSON object of the entry's counts and names: permissions added and
    -- removed, conversations and attachments deleted, an API token's label
    -- and hint, an address book's mode and contact counts.
    details TEXT
);

CREATE INDEX IF NOT EXISTS ix_audit_entries_account_at
    ON audit_entries(account_id, at);

CREATE INDEX IF NOT EXISTS ix_audit_entries_at
    ON audit_entries(at);

CREATE INDEX IF NOT EXISTS ix_audit_entries_session
    ON audit_entries(session_entry_id);

CREATE INDEX IF NOT EXISTS ix_audit_entries_deletion
    ON audit_entries(deletion_entry_id);
`;

export const MESSAGES_DDL = `-- One chat thread per account + chat handle.
CREATE TABLE IF NOT EXISTS conversations (
    -- Surrogate primary key for this conversation.
    id INTEGER PRIMARY KEY,
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Thread identity handle (\`handles.id\`); peer for 1:1, group chat id for groups.
    chat_handle_id INTEGER NOT NULL REFERENCES handles(id) ON DELETE CASCADE,
    -- Thread shape: 'individual' | 'group' (and any other values the importer writes).
    conversation_type TEXT NOT NULL,
    -- Group display title; NULL for 1:1 chats.
    group_title TEXT,
    -- The latest message time of the copy that gave group_title, in the form
    -- messages.timestamp holds; NULL with no title, or when that copy had no
    -- messages. A merge compares an incoming copy's latest message with it
    -- (docs/architecture/contacts-identities-and-messages.md).
    group_title_at TEXT,
    -- Path or name of the source file this thread came from.
    source_file TEXT NOT NULL,
    UNIQUE(account_id, chat_handle_id)
);

CREATE INDEX IF NOT EXISTS ix_conversations_account_id ON conversations (account_id);

-- One other person listed in a conversation. The account holder is never a
-- participant (ADR-0015); a message records which of the holder's addresses it
-- used in \`messages.owner_handle_id\`. A participant's contact is the one its
-- identity is on (\`contact_handles\`), so renaming or moving the identity
-- reaches every conversation at once.
CREATE TABLE IF NOT EXISTS participants (
    -- Surrogate primary key for this participant row.
    id INTEGER PRIMARY KEY,
    -- Parent conversation (\`conversations.id\`).
    conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    -- Participant identity (\`handles.id\`). A person the source named with no
    -- address has an identity of type 'other' holding the name.
    handle_id INTEGER NOT NULL REFERENCES handles(id) ON DELETE CASCADE,
    -- Display name residue from the source for this participant.
    name_alias TEXT,
    -- A participant is one person's seat in one conversation.
    UNIQUE (conversation_id, handle_id)
);

CREATE INDEX IF NOT EXISTS ix_participants_handle_id ON participants (handle_id);

-- One message in a conversation.
CREATE TABLE IF NOT EXISTS messages (
    -- Surrogate primary key for this message.
    id INTEGER PRIMARY KEY,
    -- Parent conversation (\`conversations.id\`).
    conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    -- Owning account (\`accounts.id\`) denormalized for account-scoped queries.
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Backup/source family that produced this row (for example imessage, whatsapp).
    source TEXT NOT NULL,
    -- Source-native message id; used for exact dedupe with source. The import
    -- refuses a message without one.
    guid TEXT NOT NULL CHECK (guid != ''),
    -- The instant the message was sent, to the millisecond: RFC 3339 in UTC
    -- with three fractional digits and a Z suffix (2015-03-12T18:04:22.250Z;
    -- .000 for a source that records whole seconds). One fixed form, so the
    -- text sorts in time order and lists order by it. Shown, searched and
    -- filed by day and year in the account's time zone (accounts.time_zone).
    timestamp TEXT NOT NULL,
    -- Whether the source recorded timestamp to the millisecond or in whole
    -- seconds, as the conversation file's time_precision says. The flag, never
    -- the time, decides: a millisecond time can end in .000. Within one
    -- source, a 'seconds' message is the duplicate of one that matches it in
    -- everything else with 'milliseconds' in the same second
    -- (docs/architecture/contacts-identities-and-messages.md).
    time_precision TEXT NOT NULL CHECK (time_precision IN ('seconds', 'milliseconds')),
    -- 1 = sent by the account holder; 0 = received from someone else.
    is_from_me INTEGER NOT NULL,
    -- Sender identity (\`handles.id\`); NULL when unknown.
    sender_handle_id INTEGER REFERENCES handles(id) ON DELETE SET NULL,
    -- The account holder's own address on this message (\`handles.id\`): the one
    -- it was sent from or received at, from the backup. NULL when the backup
    -- names no owner. Not necessarily one of the account's identities (ADR-0015).
    owner_handle_id INTEGER REFERENCES handles(id) ON DELETE SET NULL,
    -- Per-message transport: sms / imessage / rcs / whatsapp / …
    service TEXT,
    -- Optional subject line (for example MMS subject).
    subject TEXT,
    -- Plain-text body; may be NULL for attachment-only or announcement rows.
    body TEXT,
    -- 1 = system/announcement bubble; 0 = normal user message.
    is_announcement INTEGER NOT NULL DEFAULT 0,
    -- 1 = a reply, whether or not the message it quotes is known; 0 = not a reply.
    is_reply INTEGER NOT NULL DEFAULT 0,
    -- The guid of the message a reply quotes, when that message was in the
    -- same export; NULL otherwise. A message's reply count is the number of
    -- messages whose reply_to_guid is its guid, counted when read.
    reply_to_guid TEXT,
    -- The part of the quoted message a reply answers; NULL when not recorded.
    reply_to_part INTEGER,
    -- 'deleted_in_source_app': the person deleted it in the app it came from
    -- before the backup; 'unsent': its sender took it back. NULL for neither.
    -- The message is listed like any other either way. An Unsent message
    -- shows none of its text, so a word of it does not find the message
    -- (fts_triggers_create.sql); a Deleted one is found by its text.
    deletion TEXT CHECK (deletion IN ('deleted_in_source_app', 'unsent')),
    -- Stable order within the conversation when timestamps collide.
    sort_order INTEGER NOT NULL,
    -- Hash fingerprint for cross-source duplicate detection (chat/direction/time/body/attachments).
    content_key TEXT,
    -- Points at the kept message when this row is a flagged duplicate.
    duplicate_of INTEGER REFERENCES messages(id) ON DELETE SET NULL,
    -- Import run that inserted this row (\`imports.id\`).
    import_id INTEGER REFERENCES imports(id) ON DELETE SET NULL,
    -- When the backup that gave the message its deletion mark and text was
    -- made, in the form timestamp holds; NULL when its file did not say. A
    -- later import's copy from a later backup replaces both; one from an
    -- earlier backup changes neither
    -- (docs/architecture/contacts-identities-and-messages.md).
    backup_taken_at TEXT
);

CREATE INDEX IF NOT EXISTS ix_messages_conversation_timestamp
    ON messages (conversation_id, timestamp);
CREATE INDEX IF NOT EXISTS ix_messages_conversation_source_timestamp
    ON messages (conversation_id, source, timestamp);
CREATE INDEX IF NOT EXISTS ix_messages_account_id ON messages (account_id);
-- \`GET /v1/messages\` pages an account's messages by time; this serves the
-- default sort without a scan.
CREATE INDEX IF NOT EXISTS ix_messages_account_timestamp
    ON messages (account_id, timestamp, id);
-- \`GET /v1/contacts\` computes when the account last heard from each contact:
-- the newest message any of the contact's handles sent. This answers that
-- MAX(timestamp) per sender without a scan.
CREATE INDEX IF NOT EXISTS ix_messages_sender_timestamp
    ON messages (sender_handle_id, timestamp);
CREATE UNIQUE INDEX IF NOT EXISTS ix_messages_account_source_guid
    ON messages (account_id, source, guid);
CREATE INDEX IF NOT EXISTS ix_messages_content_key
    ON messages (content_key)
    WHERE content_key IS NOT NULL AND content_key != '';
CREATE INDEX IF NOT EXISTS ix_messages_duplicate_of
    ON messages (duplicate_of)
    WHERE duplicate_of IS NOT NULL;
-- An account identity's counts read the messages held at it (ADR-0015).
CREATE INDEX IF NOT EXISTS ix_messages_owner_handle_id ON messages (owner_handle_id);
CREATE INDEX IF NOT EXISTS ix_messages_import_id
    ON messages (import_id)
    WHERE import_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_messages_source ON messages (source);
-- A message's reply count is read by counting the replies that name it, the
-- same account, source and guid that ix_messages_account_source_guid keys it
-- by; this answers that count without a scan.
CREATE INDEX IF NOT EXISTS ix_messages_reply_to
    ON messages (account_id, source, reply_to_guid)
    WHERE reply_to_guid IS NOT NULL;

-- File or media part attached to a message.
CREATE TABLE IF NOT EXISTS attachments (
    -- Surrogate primary key for this attachment.
    id INTEGER PRIMARY KEY,
    -- Parent message (\`messages.id\`).
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    -- Relative path from the export/staging layout when known.
    path TEXT,
    -- Original filename from the source.
    original_name TEXT,
    -- MIME type of the original bytes when known.
    mime_type TEXT,
    -- 1 = sticker; 0 = ordinary attachment.
    is_sticker INTEGER NOT NULL DEFAULT 0,
    -- Optional speech-to-text or OCR text for search.
    transcription TEXT,
    -- SHA-256 hex of the stored original bytes when present.
    sha256 TEXT,
    -- Path under the assets store for the original file.
    assets_path TEXT,
    -- Original file size in bytes when known.
    size_bytes INTEGER,
    -- Why bytes are absent (for example not_exported, decrypt_failed); NULL if present.
    missing_reason TEXT,
    -- SHA-256 hex of a converted/compressed derivative used by the browser.
    derived_sha256 TEXT,
    -- Path under the assets store for the derivative file.
    derived_assets_path TEXT,
    -- MIME type of the derivative file.
    derived_mime_type TEXT,
    -- 1 when every browser shows the stored original as it is, so a viewer
    -- opens it and it gets no Preview (\`media::browser_shows\`,
    -- \`docs/architecture/media.md\` rule 2). The server's media pass decides
    -- it, and only an MP4 is opened to read its codec. 0 when it is not
    -- shown as it is, and until the pass has looked at the file.
    shown_as_is INTEGER NOT NULL DEFAULT 0 CHECK (shown_as_is IN (0, 1)),
    -- SHA-256 hex of the Thumbnail: a small JPEG of an image, or a video's
    -- first frame. NULL until the server has made it.
    thumbnail_sha256 TEXT,
    -- Path of the Thumbnail under the account's converted-media directory.
    thumbnail_assets_path TEXT,
    -- MIME type of the Thumbnail file.
    thumbnail_mime_type TEXT
);

CREATE INDEX IF NOT EXISTS ix_attachments_sha256 ON attachments (sha256);
CREATE INDEX IF NOT EXISTS ix_attachments_message_id ON attachments (message_id);

-- Assets whose Thumbnail and Preview the server still has to make. An Import
-- Run that ends adds the Assets its messages name, and the server works
-- through the rows in the background, removing each when it is done, so the
-- rows a stopped server leaves are worked on when it starts again.
CREATE TABLE IF NOT EXISTS media_queue (
    -- Account whose Asset this is (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- SHA-256 hex of the original Asset.
    sha256 TEXT NOT NULL,
    -- When the Asset was queued, in Unix seconds.
    queued_at INTEGER NOT NULL,
    PRIMARY KEY (account_id, sha256)
);

-- Reaction (tapback) on a message part.
CREATE TABLE IF NOT EXISTS tapbacks (
    -- Surrogate primary key for this reaction.
    id INTEGER PRIMARY KEY,
    -- Parent message (\`messages.id\`).
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    -- Which part of a multi-part message this reaction targets (0 = first/default).
    part_index INTEGER NOT NULL DEFAULT 0,
    -- Reaction kind from the source (for example loved, liked, emphasized).
    kind TEXT NOT NULL,
    -- Emoji glyph when the reaction is custom/emoji-based.
    emoji TEXT,
    -- 1 = reaction from the account holder; 0 = from someone else.
    is_from_me INTEGER NOT NULL,
    -- Reactor identity (\`handles.id\`); NULL when unknown.
    sender_handle_id INTEGER REFERENCES handles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_tapbacks_message_id ON tapbacks (message_id);

-- One earlier version of one part of an edited message: the text that part
-- held before an edit replaced it. messages.body is the final version; these
-- are the versions before it. Search finds a message by any of them
-- (message_versions_fts in fts_virtual.sql).
CREATE TABLE IF NOT EXISTS message_versions (
    -- Surrogate primary key; also the version's rowid in message_versions_fts.
    -- Ascending within a message in the order the source listed its versions,
    -- oldest first within each part.
    id INTEGER PRIMARY KEY,
    -- The edited message (\`messages.id\`).
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    -- Which part of a multi-part message this version belongs to (0 = first/only).
    part_index INTEGER NOT NULL DEFAULT 0,
    -- The part's text in this version.
    text TEXT NOT NULL,
    -- When this version was written, to the millisecond in the form
    -- messages.timestamp holds: the send time for the original, the edit's time for
    -- a later one. NULL when the source does not record it.
    edited_at TEXT
);

CREATE INDEX IF NOT EXISTS ix_message_versions_message_id ON message_versions (message_id);

-- Named tag a user can stamp on whole conversations.
CREATE TABLE IF NOT EXISTS message_tags (
    -- Surrogate primary key for this tag.
    id INTEGER PRIMARY KEY,
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Tag text unique per account.
    name TEXT NOT NULL,
    UNIQUE(account_id, name)
);

-- Membership of a conversation in a message tag.
CREATE TABLE IF NOT EXISTS message_tag_members (
    -- Tagged conversation (\`conversations.id\`).
    conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    -- Tag that includes the conversation (\`message_tags.id\`).
    tag_id INTEGER NOT NULL REFERENCES message_tags(id) ON DELETE CASCADE,
    PRIMARY KEY (conversation_id, tag_id)
);

-- One message a running Export Run matched when it was created. The run's
-- pages read these rows rather than its scope, so an import, a trash, or a
-- new day between pages cannot move what the run hands over. The rows are
-- deleted when the run completes or is cancelled.
CREATE TABLE IF NOT EXISTS export_messages (
    -- Export Run (\`exports.id\`).
    export_id INTEGER NOT NULL REFERENCES exports(id) ON DELETE CASCADE,
    -- The message's place in the run, from 1: oldest first by timestamp,
    -- then sort_order, then id, as they stood at creation.
    row_order INTEGER NOT NULL,
    -- Matched message (\`messages.id\`). NULL once the message is deleted: its
    -- place stays, empty, so the places after it do not move.
    message_id INTEGER REFERENCES messages(id) ON DELETE SET NULL,
    PRIMARY KEY (export_id, row_order)
);

CREATE INDEX IF NOT EXISTS ix_export_messages_message
    ON export_messages (message_id);
`;

export const STAGING_DDL = `-- Import scratch copy of conversations; cleared/promoted per account during import.
CREATE TABLE IF NOT EXISTS staging_conversations (
    -- Surrogate primary key for this staging conversation.
    id INTEGER PRIMARY KEY,
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Thread identity handle id (resolved into handles during staging).
    chat_handle_id INTEGER NOT NULL,
    -- Thread shape: 'individual' | 'group' (and any other values the importer writes).
    conversation_type TEXT NOT NULL,
    -- Group display title; NULL for 1:1 chats.
    group_title TEXT,
    -- The latest message time of the copy that gave group_title, in the form
    -- staging_messages.timestamp holds; NULL with no title, or when that copy had no
    -- messages. A merge compares an incoming copy's latest message with it
    -- (docs/architecture/contacts-identities-and-messages.md).
    group_title_at TEXT,
    -- Path or name of the source file this thread came from.
    source_file TEXT NOT NULL,
    UNIQUE(account_id, chat_handle_id)
);

-- Import scratch copy of participants.
CREATE TABLE IF NOT EXISTS staging_participants (
    -- Surrogate primary key for this staging participant.
    id INTEGER PRIMARY KEY,
    -- Parent staging conversation (\`staging_conversations.id\`).
    conversation_id INTEGER NOT NULL REFERENCES staging_conversations(id) ON DELETE CASCADE,
    -- Participant identity handle id (resolved during staging).
    handle_id INTEGER NOT NULL,
    -- Display name residue from the source for this participant.
    name_alias TEXT,
    UNIQUE(conversation_id, handle_id)
);

-- Import scratch copy of messages (no content_key / duplicate_of until promote).
CREATE TABLE IF NOT EXISTS staging_messages (
    -- Surrogate primary key for this staging message.
    id INTEGER PRIMARY KEY,
    -- Parent staging conversation (\`staging_conversations.id\`).
    conversation_id INTEGER NOT NULL REFERENCES staging_conversations(id) ON DELETE CASCADE,
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Backup/source family that produced this row.
    source TEXT NOT NULL,
    -- The message's id from the export: Apple's own for Apple Messages, otherwise
    -- the exporter's MessageGuid. Never empty; the import refuses a message without one.
    guid TEXT NOT NULL CHECK (guid != ''),
    -- The instant the message was sent, in the form messages.timestamp holds:
    -- RFC 3339 in UTC to the millisecond (2015-03-12T18:04:22.250Z).
    timestamp TEXT NOT NULL,
    -- Whether the source recorded timestamp to the millisecond or in whole
    -- seconds, as messages.time_precision.
    time_precision TEXT NOT NULL CHECK (time_precision IN ('seconds', 'milliseconds')),
    -- 1 = sent by the account holder; 0 = received from someone else.
    is_from_me INTEGER NOT NULL,
    -- Sender identity handle id; NULL when unknown.
    sender_handle_id INTEGER,
    -- The account holder's own address on this message (handle id); NULL when
    -- the backup names no owner.
    owner_handle_id INTEGER,
    -- Per-message transport: sms / imessage / rcs / whatsapp / …
    service TEXT,
    -- Optional subject line.
    subject TEXT,
    -- Plain-text body; may be NULL for attachment-only or announcement rows.
    body TEXT,
    -- 1 = system/announcement bubble; 0 = normal user message.
    is_announcement INTEGER NOT NULL DEFAULT 0,
    -- 1 = a reply, whether or not the message it quotes is known; 0 = not a reply.
    is_reply INTEGER NOT NULL DEFAULT 0,
    -- The guid of the message a reply quotes, when that message was in the
    -- same export; NULL otherwise. A message's reply count is the number of
    -- messages whose reply_to_guid is its guid, counted when read.
    reply_to_guid TEXT,
    -- The part of the quoted message a reply answers; NULL when not recorded.
    reply_to_part INTEGER,
    -- Deleted in the source app or Unsent, as \`messages.deletion\`.
    deletion TEXT CHECK (deletion IN ('deleted_in_source_app', 'unsent')),
    -- Stable order within the conversation when timestamps collide.
    sort_order INTEGER NOT NULL,
    -- Import run that staged this row (\`imports.id\`).
    import_id INTEGER REFERENCES imports(id) ON DELETE SET NULL,
    -- When the backup this row was read from was made, in the form timestamp
    -- holds; NULL when its file did not say. Between two copies of one message
    -- from one source, the copy from the later backup decides its deletion mark
    -- and text (docs/architecture/contacts-identities-and-messages.md).
    backup_taken_at TEXT
);

CREATE INDEX IF NOT EXISTS ix_staging_messages_conversation_timestamp
    ON staging_messages (conversation_id, timestamp);
CREATE INDEX IF NOT EXISTS ix_staging_messages_account_id ON staging_messages (account_id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_staging_messages_account_source_guid
    ON staging_messages (account_id, source, guid);

-- Import scratch copy of attachments.
CREATE TABLE IF NOT EXISTS staging_attachments (
    -- Surrogate primary key for this staging attachment.
    id INTEGER PRIMARY KEY,
    -- Parent staging message (\`staging_messages.id\`).
    message_id INTEGER NOT NULL REFERENCES staging_messages(id) ON DELETE CASCADE,
    -- Relative path from the export/staging layout when known.
    path TEXT,
    -- Original filename from the source.
    original_name TEXT,
    -- MIME type of the original bytes when known.
    mime_type TEXT,
    -- 1 = sticker; 0 = ordinary attachment.
    is_sticker INTEGER NOT NULL DEFAULT 0,
    -- Optional speech-to-text or OCR text for search.
    transcription TEXT,
    -- SHA-256 hex of the stored original bytes when present.
    sha256 TEXT,
    -- Path under the assets store for the original file.
    assets_path TEXT,
    -- Original file size in bytes when known.
    size_bytes INTEGER,
    -- Why bytes are absent; NULL if present.
    missing_reason TEXT,
    -- SHA-256 hex of a converted/compressed derivative.
    derived_sha256 TEXT,
    -- Path under the assets store for the derivative file.
    derived_assets_path TEXT,
    -- MIME type of the derivative file.
    derived_mime_type TEXT
);

CREATE INDEX IF NOT EXISTS ix_staging_attachments_sha256 ON staging_attachments (sha256);
CREATE INDEX IF NOT EXISTS ix_staging_attachments_message_id ON staging_attachments (message_id);

-- Import scratch copy of tapbacks.
CREATE TABLE IF NOT EXISTS staging_tapbacks (
    -- Surrogate primary key for this staging reaction.
    id INTEGER PRIMARY KEY,
    -- Parent staging message (\`staging_messages.id\`).
    message_id INTEGER NOT NULL REFERENCES staging_messages(id) ON DELETE CASCADE,
    -- Which part of a multi-part message this reaction targets (0 = first/default).
    part_index INTEGER NOT NULL DEFAULT 0,
    -- Reaction kind from the source (for example loved, liked, emphasized).
    kind TEXT NOT NULL,
    -- Emoji glyph when the reaction is custom/emoji-based.
    emoji TEXT,
    -- 1 = reaction from the account holder; 0 = from someone else.
    is_from_me INTEGER NOT NULL,
    -- Reactor identity handle id; NULL when unknown.
    sender_handle_id INTEGER
);

CREATE INDEX IF NOT EXISTS ix_staging_tapbacks_message_id ON staging_tapbacks (message_id);

-- Import scratch copy of message_versions: an edited message's earlier versions.
CREATE TABLE IF NOT EXISTS staging_message_versions (
    -- Surrogate primary key; ascending in the order the file listed the versions.
    id INTEGER PRIMARY KEY,
    -- Parent staging message (\`staging_messages.id\`).
    message_id INTEGER NOT NULL REFERENCES staging_messages(id) ON DELETE CASCADE,
    -- Which part of a multi-part message this version belongs to (0 = first/only).
    part_index INTEGER NOT NULL DEFAULT 0,
    -- The part's text in this version.
    text TEXT NOT NULL,
    -- When this version was written, in the form staging_messages.timestamp
    -- holds; NULL when the source does not record it.
    edited_at TEXT
);

CREATE INDEX IF NOT EXISTS ix_staging_message_versions_message_id ON staging_message_versions (message_id);
`;

export const CONTACTS_DDL = `-- Address-book person for one account.
CREATE TABLE IF NOT EXISTS contacts (
    -- Surrogate primary key for this contact row.
    id INTEGER PRIMARY KEY,
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Display name shown in the UI. Empty until something supplies a name;
    -- a contact with identities and no preferred name is Unknown.
    preferred_name TEXT NOT NULL,
    -- What made this row: 'address_book' (an address book load), 'import',
    -- or 'user'. It becomes 'user' when the person types the name. A load
    -- renames a contact of any origin without changing this, and leaves
    -- contacts its file does not list alone.
    origin TEXT NOT NULL DEFAULT 'user',
    -- When the row was first recorded. Stored and queryable; not displayed.
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    -- Address-book shape last changed (not message activity).
    last_modified TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS ix_contacts_account_id ON contacts (account_id);

-- One platform identity (phone, email, username, or other) per account.
CREATE TABLE IF NOT EXISTS handles (
    -- Surrogate primary key for this handle row.
    id INTEGER PRIMARY KEY,
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Identity string exactly as the backup/source wrote it.
    raw TEXT NOT NULL,
    -- Dedup key: E.164 when unambiguous for phones; otherwise cleaned digits/text.
    normalized TEXT NOT NULL,
    -- Human-readable reason the number needs review; NULL when normalization is trusted.
    normalized_note TEXT,
    -- Shape of the identity: 'phone' | 'email' | 'username' | 'other'.
    handle_type TEXT NOT NULL,
    -- Platform identity: 'phone' | 'whatsapp' (not per-message SMS/iMessage/RCS).
    service TEXT NOT NULL,
    -- What made this row: 'address_book' (an address book load), 'import',
    -- or 'user'. Whatever made it, an identity taken off its contact is
    -- deleted when nothing else refers to it.
    origin TEXT NOT NULL DEFAULT 'import',
    -- When the identity was first recorded. Queryable; not displayed.
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    -- When the identity last changed. Queryable; not displayed.
    last_modified TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(account_id, normalized, handle_type, service)
);

CREATE INDEX IF NOT EXISTS ix_handles_account_id ON handles (account_id);
CREATE INDEX IF NOT EXISTS ix_handles_normalized ON handles (account_id, normalized);

-- Links one handle to at most one contact within an account.
CREATE TABLE IF NOT EXISTS contact_handles (
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Linked identity (\`handles.id\`).
    handle_id INTEGER NOT NULL REFERENCES handles(id) ON DELETE CASCADE,
    -- Address-book person that owns this handle (\`contacts.id\`).
    contact_id INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    -- What made or last moved this link: 'address_book' (an address book
    -- load), 'import', or 'user'.
    origin TEXT NOT NULL DEFAULT 'import',
    PRIMARY KEY (account_id, handle_id)
);

CREATE INDEX IF NOT EXISTS ix_contact_handles_contact_id
    ON contact_handles (contact_id);

-- Named group a user can attach to contacts.
CREATE TABLE IF NOT EXISTS contact_groups (
    -- Surrogate primary key for this group.
    id INTEGER PRIMARY KEY,
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Group text unique per account.
    name TEXT NOT NULL,
    -- How the row was born: 'manual' when a person made it, 'import' when the
    -- server created it at the end of an import run. An import group is a
    -- shortcut pointing at that run and the person may delete it; the run's own
    -- record is permanent. Unknown is not stored here — its membership is
    -- computed from contact state.
    kind TEXT NOT NULL DEFAULT 'manual',
    UNIQUE(account_id, name)
);

-- Membership of a contact in a group.
CREATE TABLE IF NOT EXISTS contact_group_members (
    -- Contact in the group (\`contacts.id\`).
    contact_id INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    -- Group that includes the contact (\`contact_groups.id\`).
    group_id INTEGER NOT NULL REFERENCES contact_groups(id) ON DELETE CASCADE,
    PRIMARY KEY (contact_id, group_id)
);

-- Soft-delete marker for a conversation; chat rows stay until purge.
CREATE TABLE IF NOT EXISTS trashed_conversations (
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Conversation marked trash (\`conversations.id\`, no FK so chat can remain).
    conversation_id INTEGER NOT NULL,
    -- When the conversation entered trash (SQLite datetime string).
    trashed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (account_id, conversation_id)
);

-- Soft-delete marker for a contact. Deleting a trashed contact blanks its
-- name and removes this marker; the contact row and its handles stay.
CREATE TABLE IF NOT EXISTS trashed_contacts (
    -- Owning account (\`accounts.id\`).
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- Contact marked trash (\`contacts.id\`, no FK so contact can remain).
    contact_id INTEGER NOT NULL,
    -- When the contact entered trash (SQLite datetime string).
    trashed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (account_id, contact_id)
);
`;

export const FTS_VIRTUAL_DDL = `-- Contentless FTS5 index over message body/subject plus attachment text.
-- contentless_delete=1 lets a row be deleted by rowid alone. Without it a
-- delete has to repeat the exact text that was indexed, and any term it
-- leaves out stays in the index under that rowid, where the next message
-- given the same id is found by it.
CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING fts5(
    -- Indexed message body text (synced from messages.body).
    body,
    -- Indexed message subject text (synced from messages.subject).
    subject,
    -- Indexed attachment filenames + transcriptions for the message.
    attachment_text,
    content='',
    contentless_delete=1,
    tokenize='unicode61 remove_diacritics 2'
);

-- Contentless FTS5 index over each earlier version of an edited message
-- (message_versions.text), one row per version under the version's id.
-- Separate from messages_fts so a search can tell a message it found by its
-- final text from one it found only by an earlier version, and say which
-- version that was. Same tokenizer, so a word matches the same way in both.
CREATE VIRTUAL TABLE IF NOT EXISTS message_versions_fts USING fts5(
    -- Indexed version text (synced from message_versions.text).
    text,
    content='',
    contentless_delete=1,
    tokenize='unicode61 remove_diacritics 2'
);
`;

export const FTS_TRIGGERS_DROP_SQL = `DROP TRIGGER IF EXISTS messages_fts_ai;
DROP TRIGGER IF EXISTS messages_fts_ad;
DROP TRIGGER IF EXISTS messages_fts_au;
DROP TRIGGER IF EXISTS attachments_fts_ai;
DROP TRIGGER IF EXISTS attachments_fts_ad;
DROP TRIGGER IF EXISTS attachments_fts_au;
DROP TRIGGER IF EXISTS message_versions_fts_ai;
DROP TRIGGER IF EXISTS message_versions_fts_ad;
DROP TRIGGER IF EXISTS message_versions_fts_au;
`;

export const FTS_TRIGGERS_CREATE_SQL = `-- Keep messages_fts in step with messages and attachments. One index row
-- holds a message's body, subject, and the names and transcriptions of all
-- its attachments, so every change removes the message's row and writes it
-- again whole. messages_fts is a contentless-delete table (fts_virtual.sql):
-- DELETE by rowid removes every term the row indexed, attachment terms
-- included, without being told what they were.
--
-- An Unsent message has no index row. It reads "Unsent" and nothing else,
-- and a search finds a message by what it shows, so a word of the text or
-- file names it hides must not find it (#1758). Marking a message Unsent
-- removes its row, and taking the mark off writes it again.
CREATE TRIGGER messages_fts_ai AFTER INSERT ON messages BEGIN
    INSERT INTO messages_fts(rowid, body, subject, attachment_text)
    SELECT
        new.id,
        coalesce(new.body, ''),
        coalesce(new.subject, ''),
        (
            SELECT coalesce(
                group_concat(
                    trim(coalesce(original_name, '') || ' ' || coalesce(transcription, '')),
                    ' '
                ),
                ''
            )
            FROM attachments
            WHERE message_id = new.id
        )
    WHERE new.deletion IS NOT 'unsent';
END;

CREATE TRIGGER messages_fts_ad AFTER DELETE ON messages BEGIN
    DELETE FROM messages_fts WHERE rowid = old.id;
END;

CREATE TRIGGER messages_fts_au AFTER UPDATE OF body, subject, deletion ON messages BEGIN
    DELETE FROM messages_fts WHERE rowid = old.id;
    INSERT INTO messages_fts(rowid, body, subject, attachment_text)
    SELECT
        new.id,
        coalesce(new.body, ''),
        coalesce(new.subject, ''),
        (
            SELECT coalesce(
                group_concat(
                    trim(coalesce(original_name, '') || ' ' || coalesce(transcription, '')),
                    ' '
                ),
                ''
            )
            FROM attachments
            WHERE message_id = new.id
        )
    WHERE new.deletion IS NOT 'unsent';
END;

CREATE TRIGGER attachments_fts_ai AFTER INSERT ON attachments BEGIN
    DELETE FROM messages_fts WHERE rowid = new.message_id;
    INSERT INTO messages_fts(rowid, body, subject, attachment_text)
    SELECT
        m.id,
        coalesce(m.body, ''),
        coalesce(m.subject, ''),
        (
            SELECT coalesce(
                group_concat(
                    trim(coalesce(a.original_name, '') || ' ' || coalesce(a.transcription, '')),
                    ' '
                ),
                ''
            )
            FROM attachments a
            WHERE a.message_id = m.id
        )
    FROM messages m WHERE m.id = new.message_id AND m.deletion IS NOT 'unsent';
END;

CREATE TRIGGER attachments_fts_ad AFTER DELETE ON attachments BEGIN
    DELETE FROM messages_fts WHERE rowid = old.message_id;
    INSERT INTO messages_fts(rowid, body, subject, attachment_text)
    SELECT
        m.id,
        coalesce(m.body, ''),
        coalesce(m.subject, ''),
        (
            SELECT coalesce(
                group_concat(
                    trim(coalesce(a.original_name, '') || ' ' || coalesce(a.transcription, '')),
                    ' '
                ),
                ''
            )
            FROM attachments a
            WHERE a.message_id = m.id
        )
    FROM messages m WHERE m.id = old.message_id AND m.deletion IS NOT 'unsent';
END;

CREATE TRIGGER attachments_fts_au AFTER UPDATE OF original_name, transcription ON attachments BEGIN
    DELETE FROM messages_fts WHERE rowid = new.message_id;
    INSERT INTO messages_fts(rowid, body, subject, attachment_text)
    SELECT
        m.id,
        coalesce(m.body, ''),
        coalesce(m.subject, ''),
        (
            SELECT coalesce(
                group_concat(
                    trim(coalesce(a.original_name, '') || ' ' || coalesce(a.transcription, '')),
                    ' '
                ),
                ''
            )
            FROM attachments a
            WHERE a.message_id = m.id
        )
    FROM messages m WHERE m.id = new.message_id AND m.deletion IS NOT 'unsent';
END;

-- Keep message_versions_fts in step with message_versions: one index row per
-- version, under the version's id. Deleting a message deletes its versions
-- through ON DELETE CASCADE, which fires the delete trigger for each.
CREATE TRIGGER message_versions_fts_ai AFTER INSERT ON message_versions BEGIN
    INSERT INTO message_versions_fts(rowid, text) VALUES (new.id, new.text);
END;

CREATE TRIGGER message_versions_fts_ad AFTER DELETE ON message_versions BEGIN
    DELETE FROM message_versions_fts WHERE rowid = old.id;
END;

CREATE TRIGGER message_versions_fts_au AFTER UPDATE OF text ON message_versions BEGIN
    DELETE FROM message_versions_fts WHERE rowid = old.id;
    INSERT INTO message_versions_fts(rowid, text) VALUES (new.id, new.text);
END;
`;
